### ISSUE TITLE
Corrupted image

### ISSUE THREAD

**Issue by ardiya** [minstone/HARRISON-Dataset#1]
Please fix the image with the following path:
- instagram_dataset/sun/image_99.jpg
- instagram_dataset/family/image_2411.jpg

**Comment by w5688414** [comment]
I met the same problem,there is a problem about the:image_2411.jpg

**Comment by minstone** [comment]
Upload the mentioned images:

- instagram_dataset/sun/image_99.jpg

- instagram_dataset/family/image_2411.jpg : the original image is also corrupted.
